import { createClient } from "@supabase/supabase-js";
const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||"";const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"";export const EDUCATION_BUCKET=process.env.SUPABASE_EDUCATION_BUCKET||process.env.SUPABASE_BUCKET||"artistyar-media";const supabase=url&&key?createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}):null;
export type EducationLesson={id:string;course_id:number;section_id:string|null;title:string;description:string;slug:string|null;content:string;lesson_type:string;access_type:string;is_required:boolean;duration_seconds:number|null;sort_order:number;is_active:boolean;created_at:string;updated_at:string};
export type EducationVideo={id:string;course_id:number;lesson_id:string;title:string;description:string;storage_bucket:string;storage_path:string;mime_type:string;file_size:number|null;duration_seconds:number|null;thumbnail_path:string|null;sort_order:number;is_active:boolean;created_at:string;updated_at:string};
export function educationConfigured(){return Boolean(supabase)}function requireClient(){if(!supabase)throw new Error("supabase_not_configured");return supabase}
export async function listEducationLessons(courseId?:number){const db=requireClient();let q=db.from("educational_lessons").select("*").order("sort_order").order("created_at");if(courseId)q=q.eq("course_id",courseId);const r=await q;if(r.error)throw new Error(r.error.message);return(r.data||[])as EducationLesson[]}
export async function createEducationLesson(input:{courseId:number;title:string;description?:string;sortOrder?:number;sectionId?:string|null;content?:string;lessonType?:string;accessType?:string;isRequired?:boolean}){const db=requireClient();const r=await db.from("educational_lessons").insert({course_id:input.courseId,title:input.title.trim(),description:(input.description||"").trim(),sort_order:input.sortOrder||0,section_id:input.sectionId||null,content:input.content||"",lesson_type:input.lessonType||"video",access_type:input.accessType||"course",is_required:input.isRequired!==false,is_active:true}).select("*").single();if(r.error)throw new Error(r.error.message);return r.data as EducationLesson}
export async function updateEducationLesson(id:string,input:Partial<Pick<EducationLesson,"title"|"description"|"sort_order"|"is_active"|"section_id"|"content"|"lesson_type"|"access_type"|"is_required"|"duration_seconds"|"slug">>){const db=requireClient();const patch:any={updated_at:new Date().toISOString()};for(const k of ["title","description","sort_order","is_active","section_id","content","lesson_type","access_type","is_required","duration_seconds","slug"] as const)if(input[k]!==undefined)patch[k]=input[k];if(typeof patch.title==="string")patch.title=patch.title.trim();if(typeof patch.description==="string")patch.description=patch.description.trim();const r=await db.from("educational_lessons").update(patch).eq("id",id).select("*").single();if(r.error)throw new Error(r.error.message);return r.data as EducationLesson}
export async function deleteEducationLesson(id:string){const db=requireClient();const r=await db.from("educational_lessons").update({is_active:false,updated_at:new Date().toISOString()}).eq("id",id);if(r.error)throw new Error(r.error.message)}
export async function listEducationVideos(courseId?:number,lessonId?:string){const db=requireClient();let q=db.from("educational_videos").select("*").order("sort_order").order("created_at");if(courseId)q=q.eq("course_id",courseId);if(lessonId)q=q.eq("lesson_id",lessonId);const r=await q;if(r.error)throw new Error(r.error.message);return(r.data||[])as EducationVideo[]}
export async function createEducationVideo(input:Omit<EducationVideo,"id"|"created_at"|"updated_at">){const db=requireClient();const lesson=await db.from("educational_lessons").select("id,course_id").eq("id",input.lesson_id).eq("course_id",input.course_id).maybeSingle();if(lesson.error)throw new Error(lesson.error.message);if(!lesson.data)throw new Error("lesson_course_mismatch");const r=await db.from("educational_videos").upsert({...input,storage_bucket:input.storage_bucket||EDUCATION_BUCKET},{onConflict:"storage_bucket,storage_path"}).select("*").single();if(r.error)throw new Error(r.error.message);return r.data as EducationVideo}
export async function updateEducationVideo(id:string,input:Partial<Pick<EducationVideo,"title"|"description"|"lesson_id"|"course_id"|"sort_order"|"thumbnail_path"|"is_active"|"duration_seconds">>){const db=requireClient();if(input.lesson_id||input.course_id){const cur=await db.from("educational_videos").select("course_id,lesson_id").eq("id",id).single();if(cur.error)throw new Error(cur.error.message);const courseId=Number(input.course_id??cur.data.course_id),lessonId=String(input.lesson_id??cur.data.lesson_id);const lesson=await db.from("educational_lessons").select("id").eq("id",lessonId).eq("course_id",courseId).maybeSingle();if(lesson.error)throw new Error(lesson.error.message);if(!lesson.data)throw new Error("lesson_course_mismatch")}const r=await db.from("educational_videos").update({...input,updated_at:new Date().toISOString()}).eq("id",id).select("*").single();if(r.error)throw new Error(r.error.message);return r.data as EducationVideo}
export async function deleteEducationVideo(id:string){const db=requireClient();const r=await db.from("educational_videos").update({is_active:false,updated_at:new Date().toISOString()}).eq("id",id);if(r.error)throw new Error(r.error.message)}
export async function listEducationStorageVideos(){const db=requireClient();const roots=["","free-training","free-training-assets","educational-videos","courses"];const found:{path:string;name:string;size:number;mimeType:string;createdAt:string}[]=[];async function walk(folder:string,depth:number){if(depth>4)return;const r=await db.storage.from(EDUCATION_BUCKET).list(folder,{limit:1000,sortBy:{column:"created_at",order:"desc"}});if(r.error)return;for(const item of r.data||[]){if(!item.name||item.name===".emptyFolderPlaceholder")continue;const path=folder?folder+"/"+item.name:item.name;const mime=String(item.metadata?.mimetype||"");const lower=item.name.toLowerCase();const isVideo=mime.startsWith("video/")||[".mp4",".webm",".mov",".m4v"].some(x=>lower.endsWith(x));if(isVideo&&item.metadata)found.push({path,name:item.name,size:Number(item.metadata.size||0),mimeType:mime||"video/mp4",createdAt:String(item.created_at||"")});else if(!item.metadata)await walk(path,depth+1)}}await Promise.all(roots.map(x=>walk(x,0)));return Array.from(new Map(found.map(x=>[x.path,x])).values())}
export async function signEducationVideo(video:EducationVideo,expiresInSeconds=300){const db=requireClient();const r=await db.storage.from(video.storage_bucket||EDUCATION_BUCKET).createSignedUrl(video.storage_path,expiresInSeconds);if(r.error||!r.data?.signedUrl)throw new Error(r.error?.message||"signed_url_unavailable");return r.data.signedUrl}