import { createClient } from "@supabase/supabase-js";
import { fetchProducts, type ApiProduct } from "@/lib/rahyar-api";
const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||"";
const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"";
const db=url&&key?createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}):null;
export type EducationSection={id:string;course_id:number;title:string;sort_order:number;is_active:boolean;created_at:string;updated_at:string};
export async function listCanonicalCourses():Promise<ApiProduct[]> { return fetchProducts(); }
export async function listSections(courseId:number){if(!db)throw new Error("supabase_not_configured");const r=await db.from("educational_sections").select("*").eq("course_id",courseId).order("sort_order").order("created_at");if(r.error)throw new Error(r.error.message);return r.data as EducationSection[];}
export async function createSection(courseId:number,title:string,sortOrder=0){if(!db)throw new Error("supabase_not_configured");const r=await db.from("educational_sections").insert({course_id:courseId,title:title.trim(),sort_order:sortOrder,is_active:true}).select("*").single();if(r.error)throw new Error(r.error.message);return r.data as EducationSection;}
export async function updateSection(id:string,input:{title?:string;sortOrder?:number;isActive?:boolean}){if(!db)throw new Error("supabase_not_configured");const patch:any={updated_at:new Date().toISOString()};if(input.title!==undefined)patch.title=input.title.trim();if(input.sortOrder!==undefined)patch.sort_order=input.sortOrder;if(input.isActive!==undefined)patch.is_active=input.isActive;const r=await db.from("educational_sections").update(patch).eq("id",id).select("*").single();if(r.error)throw new Error(r.error.message);return r.data;}
export async function deleteSection(id:string){if(!db)throw new Error("supabase_not_configured");const r=await db.from("educational_sections").update({is_active:false,updated_at:new Date().toISOString()}).eq("id",id);if(r.error)throw new Error(r.error.message);}
export async function validateCourse(courseId:number){if(!db)throw new Error("supabase_not_configured");const course=(await fetchProducts()).find(x=>x.id===courseId);const [sections,lessons,videos]=await Promise.all([db.from("educational_sections").select("id,title,is_active,sort_order").eq("course_id",courseId),db.from("educational_lessons").select("id,title,section_id,is_active,sort_order,access_type,content,slug,lesson_type").eq("course_id",courseId),db.from("educational_videos").select("id,lesson_id,is_active,storage_bucket,storage_path").eq("course_id",courseId)]);if(sections.error)throw new Error(sections.error.message);if(lessons.error)throw new Error(lessons.error.message);if(videos.error)throw new Error(videos.error.message);const activeLessons=(lessons.data||[]).filter((x:any)=>x.is_active);const activeVideos=(videos.data||[]).filter((x:any)=>x.is_active);const errors:string[]=[];if(!course)errors.push("course_not_found");if(!course?.title?.trim())errors.push("course_title_missing");if(!activeLessons.length)errors.push("course_without_lessons");const ids=new Set(activeLessons.map((x:any)=>x.id));for(const l of activeLessons){if(!l.title?.trim())errors.push("lesson_title_missing:"+l.id);if(!l.section_id && (sections.data||[]).some((s:any)=>s.is_active))errors.push("lesson_without_section:"+l.id);if(l.lesson_type==="video"&&!activeVideos.some((v:any)=>v.lesson_id===l.id&&v.storage_path))errors.push("lesson_missing_media:"+l.id);if(l.slug&&activeLessons.filter((x:any)=>x.slug===l.slug).length>1)errors.push("duplicate_lesson_slug:"+l.slug);}for(const v of activeVideos)if(!ids.has(v.lesson_id))errors.push("orphan_video:"+v.id);return {course,errors,ok:errors.length===0,counts:{sections:(sections.data||[]).filter((x:any)=>x.is_active).length,lessons:activeLessons.length,videos:activeVideos.length}};}
export { db };
