import{NextResponse}from"next/server";import{cookies}from"next/headers";import{USER_SESSION_COOKIE,verifyUserSession}from"@/lib/server-admin-auth";import{ecosystemDb}from"@/lib/user-ecosystem";
export const runtime="nodejs";export const dynamic="force-dynamic";
const allowedLevels=["beginner","intermediate","advanced","pro"];const allowedFocus=["arrangement","mixing","mastering","ear_training","harmony","production","vocal","sound_design"];
const templates=[
 {title:"ساخت پایه شنیداری",skill:"ear_training",practice_game_id:"tone",description:"تشخیص دقیق تفاوت‌های شنیداری و تصمیم‌گیری با گوش.",priority:10},
 {title:"هارمونی و تصمیم‌گیری آکوردی",skill:"harmony",course_slug:"theory",practice_game_id:"theory",description:"فواصل، آکوردها و voicing را به تصمیم عملی تبدیل کن.",priority:20},
 {title:"میکس و کنترل تعادل",skill:"mixing",course_slug:"rahyar",practice_game_id:"eq",description:"EQ، masking و balance را با تمرین پروژه‌محور تثبیت کن.",priority:30},
 {title:"داینامیک و ترنزینت",skill:"dynamics",practice_game_id:"compressor",description:"Compression و transient را با گوش و پروژه تمرین کن.",priority:40},
 {title:"استریو و فاز",skill:"stereo",practice_game_id:"phase",description:"Width، polarity و correlation را در عمل تشخیص بده.",priority:50},
];
async function auth(){return verifyUserSession((await cookies()).get(USER_SESSION_COOKIE)?.value);}
export async function GET(){const s=await auth();if(!s)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});if(!ecosystemDb)return NextResponse.json({ok:false,error:"supabase_not_configured"},{status:503});const[p,r]=await Promise.all([ecosystemDb.from("user_learning_profiles").select("*").eq("user_id",s.id).maybeSingle(),ecosystemDb.from("learning_roadmap_items").select("*").eq("user_id",s.id).order("priority").order("created_at")]);return NextResponse.json({ok:true,profile:p.data||null,roadmap:r.data||[]});}
export async function POST(req:Request){const s=await auth();if(!s)return NextResponse.json({ok:false,error:"unauthorized"},{status:401});if(!ecosystemDb)return NextResponse.json({ok:false,error:"supabase_not_configured"},{status:503});const b=await req.json().catch(()=>null) as any;const level=allowedLevels.includes(String(b?.skillLevel))?String(b.skillLevel):"beginner";const focus=Array.isArray(b?.focusAreas)?b.focusAreas.filter((x:any)=>allowedFocus.includes(String(x))).slice(0,8):[];const goals=Array.isArray(b?.goals)?b.goals.map((x:any)=>String(x).slice(0,120)).filter(Boolean).slice(0,8):[];const role=String(b?.activityRole||"producer").slice(0,60);const{error:pErr}=await ecosystemDb.from("user_learning_profiles").upsert({user_id:s.id,skill_level:level,focus_areas:focus,goals,activity_role:role,onboarding_completed:true,roadmap_version:1,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(pErr)return NextResponse.json({ok:false,error:"ذخیره مسیر یادگیری ناموفق بود."},{status:500});await ecosystemDb.from("learning_roadmap_items").delete().eq("user_id",s.id);const ranked=templates.map((t,i)=>({...t,priority:t.priority+(focus.includes(t.skill)?-5:0),source:"onboarding",metadata:{skillLevel:level,focusAreas:focus,goals}}));const{data,error}=await ecosystemDb.from("learning_roadmap_items").insert(ranked.map(x=>({user_id:s.id,title:x.title,description:x.description,skill:x.skill,course_slug:x.course_slug||null,practice_game_id:x.practice_game_id||null,priority:x.priority,status:"available",source:x.source,metadata:x.metadata}))).select("*");if(error)return NextResponse.json({ok:false,error:"ساخت Roadmap ناموفق بود."},{status:500});return NextResponse.json({ok:true,profile:{user_id:s.id,skill_level:level,focus_areas:focus,goals,onboarding_completed:true},roadmap:data||[]});}
