"use client";

import { useEffect, useState } from "react";
import { Check, Film, FolderOpen, Link2, Plus, RefreshCw, Save } from "lucide-react";

type Course={id:number;title:string;price:number;is_active:boolean};
type Lesson={id:string;course_id:number;title:string;description:string;sort_order:number;is_active:boolean};
type Video={id:string;course_id:number;lesson_id:string;title:string;description:string;storage_bucket:string;storage_path:string;mime_type:string;file_size:number|null;duration_seconds:number|null;sort_order:number;is_active:boolean};
type StorageItem={path:string;name:string;size:number;mimeType:string;createdAt:string};

async function json(url:string,init?:RequestInit){const r=await fetch(url,{...init,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.detail||"درخواست ناموفق بود.");return d;}

export default function AdminEducationPage(){
 const [storageBucket,setStorageBucket]=useState("artistyar-media"),[courses,setCourses]=useState<Course[]>([]),[courseId,setCourseId]=useState(""),[lessons,setLessons]=useState<Lesson[]>([]),[lessonId,setLessonId]=useState(""),[videos,setVideos]=useState<Video[]>([]),[storage,setStorage]=useState<StorageItem[]>([]);
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[newLesson,setNewLesson]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function loadCourses(){const d=await fetch("/api/rahyar/products",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error("دوره‌ها در دسترس نیستند.");return r.json()});setCourses(d||[]);}
 async function loadLessons(id=courseId){if(!id)return;const d=await json("/api/admin/education/lessons?courseId="+id);setLessons(d);setLessonId(d[0]?.id||"");}
 async function loadVideos(){if(!courseId)return;const d=await json("/api/admin/education/videos?courseId="+courseId);setVideos(d);}
 async function loadStorage(){const d=await json("/api/admin/education/storage");setStorageBucket(d.bucket||"artistyar-media");setStorage(d.items||[]);}
 useEffect(()=>{void loadCourses().catch(e=>setError(e.message));void loadStorage().catch(()=>{})},[]);
 useEffect(()=>{if(courseId){void loadLessons().catch(e=>setError(e.message));void loadVideos().catch(e=>setError(e.message))}},[courseId]);
 useEffect(()=>{if(lessonId)void loadVideos().catch(e=>setError(e.message))},[lessonId]);
 async function addLesson(){if(!courseId||newLesson.trim().length<2)return;setBusy(true);setError("");try{await json("/api/admin/education/lessons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({courseId:Number(courseId),title:newLesson.trim()})});setNewLesson("");await loadLessons()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function connect(item:StorageItem){if(!courseId||!lessonId)return;setBusy(true);setError("");try{await json("/api/admin/education/videos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({courseId:Number(courseId),lessonId,storagePath:item.path,storageBucket,mimeType:item.mimeType,fileSize:item.size,title:title.trim()||item.name,description})});setMessage("ویدئو به درس متصل شد.");setTitle("");await loadVideos()}catch(e){setError(e instanceof Error?e.message:"اتصال ناموفق بود")}finally{setBusy(false)}}
 async function preview(v:Video){try{const d=await json("/api/admin/education/video/"+v.id);window.open(d.url,"_blank","noopener,noreferrer")}catch(e){setError(e instanceof Error?e.message:"پیش‌نمایش ناموفق بود")}}\n async function saveVideo(v:Video){setBusy(true);try{await json("/api/admin/education/videos",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:v.id,title:v.title,description:v.description,lesson_id:v.lesson_id,course_id:v.course_id,sort_order:v.sort_order,is_active:v.is_active})});setMessage("ذخیره شد.");await loadVideos()}catch(e){setError(e instanceof Error?e.message:"ذخیره ناموفق بود")}finally{setBusy(false)}}
 return <div className="space-y-6">
  <div><p className="eyebrow">/ آموزش دیجیتال</p><h2 className="mt-3 text-2xl font-semibold text-sand-50">Educational Videos</h2><p className="mt-2 text-sm leading-7 text-ink-400">ویدئوهای موجود در Supabase را بدون آپلود مجدد به Course و Lesson متصل کن.</p></div>
  {error&&<div className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-200">{error}</div>}{message&&<div className="rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-xs text-emerald-200">{message}</div>}
  <section className="card-ay p-5 space-y-4"><div className="flex items-center gap-2"><Film size={18} className="text-gold-400"/><h3 className="text-sm text-sand-50">Course / Lesson</h3></div>
   <select className="input-ay" value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">انتخاب دوره</option>{courses.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.id} · {c.title}</option>)}</select>
   {courseId&&<div className="flex flex-col gap-2 sm:flex-row"><select className="input-ay flex-1" value={lessonId} onChange={e=>setLessonId(e.target.value)}><option value="">انتخاب درس</option>{lessons.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select><input className="input-ay flex-1" value={newLesson} onChange={e=>setNewLesson(e.target.value)} placeholder="عنوان درس جدید"/><button className="btn-primary shrink-0" disabled={busy} onClick={()=>void addLesson()}><Plus size={15}/> افزودن درس</button></div>}
  </section>
  {courseId&&lessonId&&<section className="card-ay p-5 space-y-4"><div className="flex items-center justify-between"><h3 className="text-sm text-sand-50">اتصال ویدئوی موجود</h3><button className="btn-ghost !px-3 !py-2 text-xs" onClick={()=>void loadStorage()}><RefreshCw size={13}/>Storage</button></div><div className="grid gap-3 md:grid-cols-2"><input className="input-ay" value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان ویدئو (اختیاری)"/><input className="input-ay" value={description} onChange={e=>setDescription(e.target.value)} placeholder="توضیحات (اختیاری)"/></div><div className="grid gap-3 lg:grid-cols-3">{storage.map(item=><div key={item.path} className="rounded-xl border border-white/10 p-3"><p className="truncate text-xs text-sand-100" title={item.path}>{item.path}</p><p className="mt-1 text-[10px] text-ink-500">{item.mimeType} · {Math.round(item.size/1024/1024*10)/10} MB</p><button className="btn-primary mt-3 w-full !py-2 text-xs" disabled={busy} onClick={()=>void connect(item)}><Link2 size={13}/> اتصال به درس</button></div>)}</div></section>}
 {courseId&&<section className="card-ay p-5"><div className="flex items-center justify-between"><h3 className="text-sm text-sand-50">ویدئوهای متصل ({videos.length})</h3><button className="btn-ghost !px-3 !py-2 text-xs" onClick={()=>void loadVideos()}><RefreshCw size={13}/>تازه‌سازی</button></div><div className="mt-4 space-y-3">{videos.map(v=><div key={v.id} className="grid gap-3 rounded-xl border border-white/10 p-3 md:grid-cols-[1fr_1fr_auto]"><input className="input-ay" value={v.title} onChange={e=>setVideos(x=>x.map(a=>a.id===v.id?{...a,title:e.target.value}:a))}/><input className="input-ay" value={v.description} onChange={e=>setVideos(x=>x.map(a=>a.id===v.id?{...a,description:e.target.value}:a))}/><button className="btn-ghost !px-3" disabled={busy} onClick={()=>void preview(v)}><Film size={14}/> Preview</button><button className="btn-ghost !px-3" disabled={busy} onClick={()=>void saveVideo(v)}><Save size={14}/> ذخیره</button><p className="md:col-span-3 truncate text-[10px] text-ink-600">{v.storage_bucket}/{v.storage_path}</p></div>)}</div></section>}
 <section className="card-ay p-5"><div className="flex items-center gap-2"><FolderOpen size={17} className="text-gold-400"/><span className="text-sm text-sand-50">امنیت</span></div><p className="mt-2 text-xs leading-6 text-ink-400">مسیر Storage و کلید Supabase به browser داده نمی‌شود. دانشجو فقط پس از احراز دسترسی دوره، Signed URL کوتاه‌مدت دریافت می‌کند.</p></section>
 </div>;
}
