import {chatWithProvider,discoverAllModels,getConfiguredProviders,type AIProvider,type ChatMessage} from "@/lib/ai-providers";
import type {AgentProposal,AgentRun,CodingAgentConfig} from "./types";
import {DEFAULT_CODING_AGENT_CONFIG} from "./types";
type Candidate={provider:AIProvider;model:string;rank:number};
const SYSTEM="You are a modular open-source coding agent. Inspect repository context before proposing changes. Never invent files, dependencies, secrets or test results. Prefer small reviewable changes.";
async function candidates():Promise<Candidate[]>{const entries=await discoverAllModels();const providers=getConfiguredProviders();const out:Candidate[]=[];for(const e of entries){const p=providers.find(x=>x.id===e.provider.id);if(!p)continue;for(const m of e.models||p.defaultModels?.map(id=>({id,rank:0}))||[]){if(m.id&&!/embed|whisper|tts|image|audio|moderation|transcribe|sora/i.test(m.id))out.push({provider:p,model:m.id,rank:m.rank||0});}}const seen=new Set<string>();return out.sort((a,b)=>b.rank-a.rank).filter(x=>{const k=`${x.provider.id}::${x.model}`;if(seen.has(k))return false;seen.add(k);return true;});}
function json<T>(text:string):T|null{const fenced=text.match(/```json\s*([\s\S]*?)```/i)?.[1];const raw=fenced||text.match(/\{[\s\S]*\}/)?.[0];if(!raw)return null;try{return JSON.parse(raw) as T}catch{return null}}
export class CodingAgentRuntime{constructor(private readonly config:CodingAgentConfig=DEFAULT_CODING_AGENT_CONFIG){}
async plan(task:string,context=""){const pool=await candidates();const runs:AgentRun[]=[];for(let offset=0;offset<pool.length&&runs.filter(r=>r.ok).length<Math.max(2,Math.min(this.config.maxAgents,4));offset+=6){const wave=pool.slice(offset,offset+6);const rs=await Promise.all(wave.map(c=>this.run(c,`PLAN TASK:\n${task}\n\nREPOSITORY CONTEXT:\n${context.slice(0,16000)}\n\nReturn implementation plan, affected files, risks and tests.`)));runs.push(...rs);}const good=runs.filter(r=>r.ok&&r.output);if(!good.length)throw new Error("No coding agent produced a planning response.");return{runs,synthesis:good.map((r,i)=>`AGENT ${i+1} [${r.provider}/${r.model}]\n${r.output}`).join("\n\n---\n\n")};}
async propose(task:string,context:string,plan:string):Promise<AgentProposal[]>{const pool=await candidates();const proposals:AgentProposal[]=[];for(let offset=0;offset<pool.length&&proposals.length<2;offset+=6){const rs=await Promise.all(pool.slice(offset,offset+6).map(c=>this.run(c,`CODING TASK:\n${task}\n\nLEAD PLAN:\n${plan}\n\nREPOSITORY:\n${context.slice(0,30000)}\n\nReturn ONLY JSON: {"changes":[{"path":"src/...","content":"COMPLETE FILE CONTENT","reason":"..."}],"notes":"..."}`)));for(const r of rs){const p=r.output?json<{changes?:AgentProposal["changes"];notes?:string}>(r.output):null;if(r.ok&&p?.changes?.length)proposals.push({agentId:`${r.provider}/${r.model}`,provider:r.provider,model:r.model,changes:p.changes,notes:p.notes});}}return proposals;}
private async run(c:Candidate,prompt:string):Promise<AgentRun>{const started=Date.now();const messages:ChatMessage[]=[{role:"system",content:SYSTEM},{role:"user",content:prompt}];try{const output=await Promise.race([chatWithProvider(c.provider,c.model,messages,"artistyar-coding-agent-runtime"),new Promise<string>((_,reject)=>setTimeout(()=>reject(new Error("Agent timeout")),this.config.timeoutMs))]);return{id:crypto.randomUUID(),role:"coder",provider:c.provider.id,model:c.model,ok:true,output,durationMs:Date.now()-started};}catch(error){return{id:crypto.randomUUID(),role:"coder",provider:c.provider.id,model:c.model,ok:false,error:error instanceof Error?error.message:String(error),durationMs:Date.now()-started};}}
}