"use client";

import { useEffect, useState } from "react";
import { BookOpen, History, Search } from "lucide-react";

type ClassRow = { id: number; name: string; teacher: string | null; duration_minutes: number; monthly_sessions: number; active_students: number };
type Enrollment = { id: number; course_name: string; status: string; payment_model: string; remaining_sessions: number; completed_sessions: number; created_at: string };

const labels: Record<string, string> = { active: "فعال", paused: "متوقف", ended: "پایان‌یافته", monthly: "ماهانه", term: "ترمی" };

export default function AdminEnrollmentsPage() {
  const [classes, setClasses] = useState<ClassRow[]>([]);
  const [studentId, setStudentId] = useState("");
  const [history, setHistory] = useState<Enrollment[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/rahyar/admin/classes", { cache: "no-store", credentials: "include" }).then((r) => r.json()).then(setClasses).catch(() => setError("دریافت کلاس‌ها ناموفق بود.")); }, []);
  async function loadHistory() { if (!/^\d+$/.test(studentId)) return setError("شناسه عددی هنرجو را وارد کن."); setError(""); const response = await fetch(`/api/rahyar/admin/students/${studentId}/enrollments`, { cache: "no-store", credentials: "include" }); const data = await response.json(); if (!response.ok) return setError(data.error || "دریافت سوابق ناموفق بود."); setHistory(data); }
  return <div className="space-y-6"><div><p className="eyebrow">/ آموزش و ثبت‌نام</p><h2 className="mt-3 text-2xl font-semibold text-sand-50">کلاس‌های فعال و سوابق ثبت‌نام</h2><p className="mt-2 text-sm leading-7 text-ink-400">تعداد هنرجوی فعال هر کلاس و تاریخچه ثبت‌نام هر هنرجو از دیتابیس مشترک نمایش داده می‌شود.</p></div>{error ? <p className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-300">{error}</p> : null}<section><h3 className="mb-3 flex items-center gap-2 text-base font-medium text-sand-50"><BookOpen size={17} className="text-gold-400" />کلاس‌های فعال</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{classes.map((item) => <article key={item.id} className="card-ay p-5"><div className="flex items-start justify-between gap-3"><h4 className="font-medium text-sand-50">{item.name}</h4><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] text-emerald-300">فعال</span></div><p className="mt-3 text-xs text-ink-500">مدرس: {item.teacher || "ثبت نشده"} · {item.duration_minutes} دقیقه</p><p className="mt-4 text-2xl font-semibold text-gold-400">{item.active_students}</p><p className="text-xs text-ink-500">هنرجوی فعال</p></article>)}{!classes.length ? <p className="card-ay p-5 text-sm text-ink-500">کلاس فعال ثبت نشده یا تنظیمات backend کامل نیست.</p> : null}</div></section><section className="card-ay p-5"><h3 className="flex items-center gap-2 text-base font-medium text-sand-50"><History size={17} className="text-gold-400" />سوابق ثبت‌نام هنرجو</h3><p className="mt-2 text-xs text-ink-500">شناسه هنرجو را از صفحه هنرجوها وارد کن.</p><div className="mt-4 flex gap-2"><input className="input-ay max-w-xs" inputMode="numeric" value={studentId} onChange={(event) => setStudentId(event.target.value)} placeholder="مثلاً ۱۲۳" /><button className="btn-primary !px-4" onClick={() => void loadHistory()}><Search size={15} />نمایش سوابق</button></div><div className="mt-5 space-y-2">{history.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/[.07] bg-white/[.02] p-4 text-sm"><div><strong className="text-sand-100">{item.course_name}</strong><p className="mt-1 text-xs text-ink-500">{labels[item.payment_model] || item.payment_model} · {new Date(item.created_at).toLocaleDateString("fa-IR")}</p></div><div className="text-left text-xs text-ink-400"><span className="text-gold-400">{labels[item.status] || item.status}</span><br />باقی‌مانده: {item.remaining_sessions} · تکمیل‌شده: {item.completed_sessions}</div></div>)}{history.length === 0 ? <p className="text-sm text-ink-500">هنوز سابقه‌ای برای نمایش انتخاب نشده است.</p> : null}</div></section></div>;
}
