"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, Music2, Play } from "lucide-react";

const roots=["C","D","E","F","G","A","B"];
const intervals=[["Minor 2nd",1],["Major 2nd",2],["Minor 3rd",3],["Major 3rd",4],["Perfect 4th",5],["Tritone",6],["Perfect 5th",7],["Major 6th",9],["Minor 7th",10],["Octave",12]] as const;
const chords=[["Major", [0,4,7]],["Minor",[0,3,7]],["Diminished",[0,3,6]],["Augmented",[0,4,8]],["Sus4",[0,5,7]]] as const;
const freq=(m:number)=>440*Math.pow(2,(m-69)/12);
function tone(m:number,d=.7){if(typeof window==="undefined")return;const A=window.AudioContext||(window as any).webkitAudioContext;if(!A)return;const c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq(m);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.12,c.currentTime+.03);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d+.04);setTimeout(()=>void c.close(),(d+.2)*1000)}
export function TheoryLab({onBack}:{onBack:()=>void}){
 const [mode,setMode]=useState<"interval"|"chord">("interval"); const [root,setRoot]=useState("C"); const [answer,setAnswer]=useState<string|null>(null);
 const target=useMemo(()=>mode==="interval"?intervals[Math.floor(Math.random()*intervals.length)]:chords[Math.floor(Math.random()*chords.length)],[mode,answer]);
 const play=()=>{const base=60+roots.indexOf(root); if(mode==="interval"){tone(base);setTimeout(()=>tone(base+target[1]),220)}else target[1].forEach((n,i)=>setTimeout(()=>tone(base+n,.8),i*140))};
 const options=mode==="interval"?intervals.map(x=>x[0]):chords.map(x=>x[0]);
 const correct=answer===String(target[0]);
 return <section className="mt-10"><button type="button" className="btn-ghost !px-4 !py-2 text-xs" onClick={onBack}><ArrowLeft size={14}/> بازگشت</button><div className="card-ay mt-5 p-6 sm:p-10"><div className="mx-auto max-w-2xl text-center"><Music2 className="mx-auto text-violet-300" size={35}/><p className="eyebrow mt-5">THEORY LAB · LEVEL UP</p><h1 className="mt-3 text-2xl font-semibold text-sand-50">گوش موسیقیایی را از پایه تا حرفه‌ای بساز.</h1><p className="mt-3 text-sm leading-8 text-ink-400">فاصله‌ها و کیفیت آکوردها را بشنو؛ هدف این بخش تبدیل تئوری به مهارت شنیداری است.</p><div className="mt-6 flex justify-center gap-2"><button className={`rounded-xl px-4 py-2 text-xs ${mode==="interval"?"bg-violet-400/15 text-violet-200":"bg-white/[.04] text-ink-500"}`} onClick={()=>{setMode("interval");setAnswer(null)}}>Intervals</button><button className={`rounded-xl px-4 py-2 text-xs ${mode==="chord"?"bg-violet-400/15 text-violet-200":"bg-white/[.04] text-ink-500"}`} onClick={()=>{setMode("chord");setAnswer(null)}}>Chords</button></div><div className="mt-5 flex items-center justify-center gap-2"><select className="rounded-xl border border-white/10 bg-ink-950 px-3 py-2 text-sm" value={root} onChange={e=>setRoot(e.target.value)}>{roots.map(r=><option key={r}>{r}</option>)}</select><button className="btn-primary !px-5 !py-2" onClick={play}><Play size={15} fill="currentColor"/> پخش</button></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{options.map(o=><button key={o} disabled={!!answer} onClick={()=>setAnswer(o)} className={`rounded-xl border p-3 text-sm ${answer?o===String(target[0])?"border-emerald-400/40 bg-emerald-400/10 text-emerald-200":o===answer?"border-red-400/40 text-red-200":"border-white/10 text-ink-500":"border-white/10 text-ink-300 hover:border-violet-400/40"}`}>{o}</button>)}</div>{answer?<p className={`mt-5 text-sm ${correct?"text-emerald-200":"text-red-200"}`}>{correct?"درست!":"پاسخ درست: "+String(target[0])}</p>:null}<button className="btn-primary mt-6" onClick={()=>setAnswer(null)}>Level بعدی</button></div></div></section>
}
