"use client";
import Link from "next/link";import{useEffect,useState}from"react";import{FolderKanban,FileAudio,Brain,BookOpen,ArrowLeft,Plus}from"lucide-react";import{RequireAuth}from "@/components/RequireAuth";
type Project={id:string;name:string;description:string;status:string;updated_at:string};type Road={id:string;title:string;description:string;skill:string;practice_game_id?:string;course_slug?:string;practiceAttempts:number;practiceAccuracy:number;status:string};
export default function MyArtistYarPage(){return <RequireAuth role="student"><My/></RequireAuth>}
function My(){const[p,setP]=useState<Project[]>([]),[road,setRoad]=useState<Road[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{Promise.all([fetch("/api/user/projects",{cache:"no-store"}).then(r=>r.json()),fetch("/api/user/learning",{cache:"no-store"}).then(r=>r.json())]).then(([a,b])=>{setP(a.items||[]);setRoad(b.roadmap||[])}).catch(()=>{}).finally(()=>setLoading(false))},[]);
return <main className="container-ay py-10 sm:py-14"><div className="mb-8"><p className="eyebrow">MY ARTISTYAR</p><h1 className="mt-2 text-3xl font-semibold text-sand-50">مرکز شخصی ساختن و یادگیری</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-ink-400">دوره، تمرین، تحلیل، AI، پروژه و فایل‌ها در یک مسیر واحد؛ هر کاری که انجام می‌دهی باید به قدم بعدی یادگیریت وصل شود.</p></div>
<div className="grid gap-3 sm:grid-cols-5">{[["Learn","/learn",BookOpen],["Practice","/practice",Brain],["AI","/ai",Brain],["Studio","/studio",FileAudio],["پروژه‌ها","/projects",FolderKanban]].map(([t,h,I]:any)=><Link key={h} href={h} className="card-ay p-4 transition hover:border-gold-400/25"><I size={18} className="text-gold-300"/><strong className="mt-3 block text-sm text-sand-50">{t}</strong><span className="mt-1 text-[11px] text-ink-500">ورود</span></Link>)}</div>
<section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="card-ay p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">ROADMAP</p><h2 className="mt-1 text-xl text-sand-50">قدم بعدی تو</h2></div><Link href="/learn" className="text-xs text-gold-300">مشاهده کامل ←</Link></div>{loading?<p className="mt-5 text-sm text-ink-500">در حال بارگذاری…</p>:!road.length?<div className="mt-5 rounded-xl border border-dashed border-white/10 p-5 text-sm text-ink-500">هنوز مسیر شخصی ساخته نشده. <Link href="/learn" className="text-gold-300">Onboarding را شروع کن.</Link></div>:<div className="mt-5 space-y-3">{road.slice(0,4).map(x=><div key={x.id} className="rounded-xl border border-white/[.07] p-4"><div className="flex justify-between gap-3"><strong className="text-sm text-sand-50">{x.title}</strong><span className="text-xs text-cyan-300">{x.practiceAccuracy?x.practiceAccuracy+"% دقت":"شروع نشده"}</span></div><p className="mt-1 text-xs leading-6 text-ink-500">{x.description}</p><div className="mt-3 flex gap-2">{x.course_slug&&<Link href={"/courses/"+x.course_slug} className="text-[11px] text-gold-300">یادگیری ←</Link>}{x.practice_game_id&&<Link href={"/practice?game="+x.practice_game_id} className="text-[11px] text-cyan-300">تمرین ←</Link>}</div></div>)}</div>}</div>
<div className="card-ay p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">PROJECTS</p><h2 className="mt-1 text-xl text-sand-50">پروژه‌های من</h2></div><Link href="/projects" className="text-xs text-gold-300">همه</Link></div>{loading?<p className="mt-5 text-sm text-ink-500">…</p>:<div className="mt-5 space-y-2">{p.slice(0,5).map(x=><Link href={"/projects/"+x.id} key={x.id} className="flex items-center gap-3 rounded-xl border border-white/[.07] p-3 hover:border-gold-400/20"><FolderKanban size={16} className="text-gold-300"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-sand-50">{x.name}</strong><span className="text-[10px] text-ink-500">{x.status}</span></span><ArrowLeft size={14}/></Link>)}{!p.length&&<Link href="/projects" className="flex items-center gap-2 rounded-xl border border-dashed border-white/10 p-4 text-sm text-ink-400"><Plus size={15}/> اولین پروژه را بساز</Link>}</div>}</div></section>
<div className="mt-6 grid gap-3 sm:grid-cols-3"><Link href="/files" className="card-ay p-4"><FileAudio size={18} className="text-cyan-300"/><strong className="mt-3 block text-sm text-sand-50">My Files</strong><span className="text-xs text-ink-500">فایل‌ها، نسخه‌ها و انتقال بین پروژه‌ها</span></Link><Link href="/practice" className="card-ay p-4"><Brain size={18} className="text-violet-300"/><strong className="mt-3 block text-sm text-sand-50">Practice</strong><span className="text-xs text-ink-500">ضعف‌ها را پیدا کن و تمرین بعدی را بگیر</span></Link><Link href="/music-analyzer" className="card-ay p-4"><FileAudio size={18} className="text-cyan-300"/><strong className="mt-3 block text-sm text-sand-50">Analyze</strong><span className="text-xs text-ink-500">تحلیل را مستقیماً به پروژه وصل کن</span></Link></div></main>}
