"use client";

import { useEffect, useState } from "react";
import { Activity, Bot, Eye, GraduationCap, Users } from "lucide-react";

type Summary = { site: { page_views_7d: number; page_views_30d: number; unique_visitors_30d: number; top_paths: { path: string; count: number }[] }; education: { active_classes: number; active_enrollments: number; total_enrollments: number; students: number }; ai_agent: { admin_ai_events_30d: number; source: string } };

export default function AdminAnalyticsPage() {
  const [data, setData] = useState<Summary | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/rahyar/admin/analytics", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error || "تحلیل در دسترس نیست."); setData(body); }).catch((cause) => setError(cause instanceof Error ? cause.message : "تحلیل در دسترس نیست.")); }, []);
  const cards = data ? [{ label: "بازدید ۷ روز اخیر", value: data.site.page_views_7d, icon: Eye }, { label: "بازدید ۳۰ روز اخیر", value: data.site.page_views_30d, icon: Activity }, { label: "بازدیدکننده یکتا", value: data.site.unique_visitors_30d, icon: Users }, { label: "کلاس فعال", value: data.education.active_classes, icon: GraduationCap }, { label: "ثبت‌نام فعال", value: data.education.active_enrollments, icon: Users }, { label: "رویداد AI Agent", value: data.ai_agent.admin_ai_events_30d, icon: Bot }] : [];
  return <div className="space-y-6"><div><p className="eyebrow">/ تحلیل مدیریتی</p><h2 className="mt-3 text-2xl font-semibold text-sand-50">تحلیل سایت، آموزش و AI Agent</h2><p className="mt-2 text-sm leading-7 text-ink-400">آمار ۳۰ روز اخیر از دیتابیس ثبت می‌شود؛ IP خام ذخیره نمی‌شود و بازدیدهای پنل ادمین محاسبه نمی‌شوند.</p></div>{error ? <p className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-300">{error}</p> : null}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(({ label, value, icon: Icon }) => <div className="card-ay p-5" key={label}><Icon size={18} className="text-gold-400" /><p className="mt-4 text-xs text-ink-500">{label}</p><p className="mt-2 text-3xl font-semibold text-sand-50">{value.toLocaleString("fa-IR")}</p></div>)}</div>{data ? <section className="card-ay p-5"><h3 className="font-medium text-sand-50">صفحه‌های پربازدید در ۳۰ روز</h3><div className="mt-4 space-y-3">{data.site.top_paths.map((item) => <div className="flex items-center justify-between gap-3 text-sm" key={item.path}><span className="truncate text-ink-300" dir="ltr">{item.path}</span><span className="text-gold-400">{item.count.toLocaleString("fa-IR")}</span></div>)}{!data.site.top_paths.length ? <p className="text-sm text-ink-500">هنوز داده‌ای جمع نشده است؛ بعد از deploy بازدیدها ثبت می‌شوند.</p> : null}</div></section> : null}<section className="card-ay p-5 text-sm leading-7 text-ink-400"><div className="flex items-center gap-2 text-sand-100"><Bot size={17} className="text-gold-400" />منبع تحلیل AI Agent</div><p className="mt-3">تعداد رویدادهای مدیریتی AI از audit log backend استخراج می‌شود. برای تحلیل دقیق‌تر در فاز بعد می‌توانیم conversation، intent، خطای provider، زمان پاسخ و رضایت هنرجو را به‌صورت جداگانه ثبت کنیم.</p></section></div>;
}
