create table if not exists public.practice_skill_profiles (
  user_id text primary key,
  total_xp integer not null default 0,
  overall_level integer not null default 1,
  streak integer not null default 0,
  last_practice_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.practice_skill_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  skill text not null,
  game_id text not null,
  xp integer not null default 0,
  accuracy numeric(5,2) not null default 0,
  difficulty numeric(6,3) not null default 0,
  correct boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.practice_daily_missions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  mission_date date not null,
  mission_key text not null,
  skill text not null,
  title text not null,
  target integer not null default 5,
  progress integer not null default 0,
  xp_reward integer not null default 50,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, mission_date, mission_key)
);

create index if not exists practice_skill_events_user_idx on public.practice_skill_events(user_id, created_at desc);
create index if not exists practice_skill_events_skill_idx on public.practice_skill_events(user_id, skill, created_at desc);
create index if not exists practice_daily_missions_user_date_idx on public.practice_daily_missions(user_id, mission_date);

alter table public.practice_skill_profiles enable row level security;
alter table public.practice_skill_events enable row level security;
alter table public.practice_daily_missions enable row level security;

create or replace function public.practice_skill_level(xp integer)
returns integer language sql immutable as $$
  select least(500, greatest(1, floor(greatest(0, coalesce(xp,0)) / 100.0)::integer + 1));
$$;