-- ArtistYar Practice full bootstrap (idempotent).
-- Prefer pasting PRACTICE_FULL_SQL.sql from project artifacts into Supabase SQL Editor for complete schema.
-- This file marks the migration slot in git.

-- Core progress table (minimum required for daily limits)
create table if not exists public.practice_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  username text not null default '',
  full_name text not null default '',
  game_id text not null,
  score integer not null default 0,
  accuracy numeric(5,2) not null default 0,
  streak integer not null default 0,
  best_score integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  played_at timestamptz not null default now()
);
create index if not exists practice_records_user_idx on public.practice_records(user_id, played_at desc);
create index if not exists practice_records_score_idx on public.practice_records(score desc);
create index if not exists practice_records_game_idx on public.practice_records(game_id, score desc);

create table if not exists public.practice_subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  status text not null default 'active',
  price_toman integer not null default 40000,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists practice_subscriptions_user_idx on public.practice_subscriptions(user_id, expires_at desc);
