-- Phase 3: canonical education extensions. Courses remain the existing RahYar product IDs.
create table if not exists public.educational_sections (
  id uuid primary key default gen_random_uuid(),
  course_id bigint not null,
  title text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists educational_sections_course_idx on public.educational_sections(course_id, sort_order, created_at);
alter table public.educational_sections enable row level security;

alter table public.educational_lessons
  add column if not exists section_id uuid references public.educational_sections(id) on delete set null,
  add column if not exists slug text,
  add column if not exists content text not null default '',
  add column if not exists lesson_type text not null default 'video',
  add column if not exists access_type text not null default 'course',
  add column if not exists is_required boolean not null default true,
  add column if not exists duration_seconds integer,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists updated_at timestamptz not null default now();
create index if not exists educational_lessons_section_idx on public.educational_lessons(section_id, sort_order, created_at);
create unique index if not exists educational_lessons_course_slug_uidx on public.educational_lessons(course_id, slug) where slug is not null and slug <> '';

create table if not exists public.educational_resources (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid not null references public.educational_lessons(id) on delete cascade,
  title text not null,
  kind text not null default 'download',
  media_id uuid,
  storage_bucket text,
  storage_path text,
  url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists educational_resources_lesson_idx on public.educational_resources(lesson_id, sort_order, created_at);
alter table public.educational_resources enable row level security;

create table if not exists public.educational_learning_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  course_id bigint not null,
  lesson_id uuid not null references public.educational_lessons(id) on delete cascade,
  event_type text not null,
  position_seconds integer not null default 0 check (position_seconds >= 0),
  occurred_at timestamptz not null default now()
);
create index if not exists educational_learning_activity_user_idx on public.educational_learning_activity(user_id, occurred_at desc);
create index if not exists educational_learning_activity_course_idx on public.educational_learning_activity(course_id, occurred_at desc);
alter table public.educational_learning_activity enable row level security;

create table if not exists public.educational_course_completions (
  user_id bigint not null,
  course_id bigint not null,
  completed_at timestamptz not null default now(),
  primary key(user_id, course_id)
);
alter table public.educational_course_completions enable row level security;

alter table public.educational_video_progress
  add column if not exists first_accessed_at timestamptz,
  add column if not exists completed_at timestamptz;
create index if not exists educational_video_progress_completed_idx on public.educational_video_progress(user_id, completed, updated_at desc);
