create table if not exists public.practice_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  username text not null,
  full_name text not null,
  game_id text not null,
  score integer not null default 0,
  accuracy numeric(5,2) not null default 0,
  streak integer not null default 0,
  best_score integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  played_at timestamptz not null default now()
);

create index if not exists practice_records_user_idx on public.practice_records(user_id, played_at desc);
create index if not exists practice_records_score_idx on public.practice_records(score desc);
create index if not exists practice_records_game_idx on public.practice_records(game_id, score desc);

alter table public.practice_records enable row level security;

comment on table public.practice_records is 'ArtistYar practice sessions, daily challenge progress and leaderboard source.';
