create table if not exists public.practice_subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  status text not null default 'active' check (status in ('active','expired','cancelled')),
  price_toman integer not null default 40000,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists practice_subscriptions_user_idx on public.practice_subscriptions(user_id, expires_at desc);
alter table public.practice_subscriptions enable row level security;

create table if not exists public.practice_rewards (
  id bigint generated by default as identity primary key,
  user_id text not null,
  reward_month text not null,
  active_days integer not null default 0,
  month_xp integer not null default 0,
  discount_percent integer not null default 20,
  granted_at timestamptz not null default now(),
  unique(user_id, reward_month)
);

create index if not exists practice_rewards_user_idx on public.practice_rewards(user_id, reward_month desc);
alter table public.practice_rewards enable row level security;
