import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { autoChat, type ChatMessage } from "@/lib/ai-providers";
import { cookies } from "next/headers";
import { ADMIN_SESSION_COOKIE, USER_SESSION_COOKIE, verifyAdminSession, verifyUserSession } from "@/lib/server-admin-auth";

export const runtime="nodejs"; export const dynamic="force-dynamic";
const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||"";
const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"";
const db=url&&key?createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}):null;
const FREE_LIMIT=1;
type Metrics=Record<string,number>;
function fallback(m:Metrics){const l=m.lowPct||0,h=m.highPct||0,c=m.crestFactorDb||0,u=m.approxLufs||-14;return {matchScore:Math.round(Math.max(0,Math.min(100,76-Math.max(0,(m.clipPct||0)*20)-Math.max(0,Math.abs(u+10)-8)))),summary:"تحلیل بر پایه متریک‌های واقعی فایل در مرورگر انجام شد؛ برای تصمیم نهایی level-match و A/B با رفرنس ضروری است.",descriptors:{tonal:l>45?"لو-اند سنگین":h>35?"بالا/برایت زیاد":"تونال نسبتاً متعادل",stereo:(m.stereoWidth||0)>45?"Wide":"Focused",dynamics:c<7?"فشرده":c>14?"داینامیک باز":"متوسط",loudness:u>-9?"بلند":u<-16?"آرام":"متوسط"},eq:[l>45?"Low/Sub را 1–3dB کنترل کن.":"Low-end فعلاً متعادل است.",h>35?"High را برای harshness/de-ess بررسی کن.":"High-end نیاز به اصلاح شدید نشان نمی‌دهد."],compression:c<7?"کمپرس بیشتر را فعلاً کم کن؛ transient را حفظ کن.":"کمپرس ملایم 1–3dB GR را تست کن.",limiting:(m.truePeakDbfs||-1)>-1?"True Peak بالاست؛ سقف را حدود -1 dBTP بگذار.":"Headroom مناسب است.",roadmap:["Level-match با رفرنس.","Mono/phase را چک کن.","EQ کاهشی قبل از boost.","Compression را با GR تنظیم کن.","Limiter و True Peak را در پایان کنترل کن."],quickFixes:[(m.clipPct||0)>0?"کلیپینگ را رفع کن.":"کلیپ واضح شناسایی نشد.",(m.stereoCorrelation||1)<0?"فاز/استریو را بررسی کن.":"Correlation قابل‌قبول است."],source:"browser-metrics"}}
async function auth(userId:string,telegramId:string){const s=await cookies();if(verifyAdminSession(s.get(ADMIN_SESSION_COOKIE)?.value))return true;const u=verifyUserSession(s.get(USER_SESSION_COOKIE)?.value);return !!u&&(u.id===userId||(!userId&&u.telegramId===telegramId));}
export async function GET(req:Request){const p=new URL(req.url).searchParams;const uid=p.get("userId")||"";if(!db)return NextResponse.json({ok:true,dailyLimit:FREE_LIMIT,used:0,remaining:1,pro:false});const {data}=await db.from("practice_records").select("id").eq("user_id",uid).eq("game_id","music-analyzer").gte("played_at",new Date(new Date().toISOString().slice(0,10)+"T00:00:00Z").toISOString());const {data:sub}=await db.from("practice_subscriptions").select("id").eq("user_id",uid).eq("status","active").gt("expires_at",new Date().toISOString()).limit(1);const pro=!!sub?.length;const used=data?.length||0;return NextResponse.json({ok:true,dailyLimit:pro?0:1,used,remaining:pro?0:Math.max(0,1-used),pro,unlimited:pro})}
export async function POST(req:Request){const b=await req.json().catch(()=>({}));const uid=String(b.userId||"");const tid=String(b.telegramId||"");if(!(await auth(uid,tid)))return NextResponse.json({ok:false,error:"unauthorized"},{status:401});const m=(b.metrics||{}) as Metrics;if(!db)return NextResponse.json({ok:true,analysis:fallback(m),unlimited:true});const [rows,subs]=await Promise.all([db.from("practice_records").select("id").eq("user_id",uid).eq("game_id","music-analyzer").gte("played_at",new Date(new Date().toISOString().slice(0,10)+"T00:00:00Z").toISOString()),db.from("practice_subscriptions").select("id").eq("user_id",uid).eq("status","active").gt("expires_at",new Date().toISOString()).limit(1)]);const pro=!!subs.data?.length;const used=rows.data?.length||0;if(!pro&&used>=FREE_LIMIT)return NextResponse.json({ok:false,code:"daily_limit_reached",dailyLimit:1,used,remaining:0},{status:429});let analysis=fallback(m);try{const msgs:ChatMessage[]=[{role:"system",content:"تو مهندس میکس حرفه‌ای هستی. فقط JSON معتبر با کلیدهای matchScore,summary,descriptors{tonal,stereo,dynamics,loudness},eq[],compression,limiting,roadmap[],quickFixes[]. همه متن‌ها فارسی و عملی."},{role:"user",content:"این متریک‌های واقعی فایل هستند: "+JSON.stringify(m)}];const ai=await autoChat(msgs,undefined,undefined,"artistyar-music-analyzer");const raw=ai.reply.match(/\{[\s\S]*\}/)?.[0];if(raw){const p=JSON.parse(raw);analysis={...analysis,...p,source:"ai:"+ai.provider+"/"+ai.model}}}catch{}try{await db.from("practice_records").insert({user_id:uid,username:String(b.username||uid).slice(0,120),full_name:String(b.fullName||b.username||uid).slice(0,160),game_id:"music-analyzer",score:Number(analysis.matchScore)||0,accuracy:Number(analysis.matchScore)||0,streak:0,best_score:Number(analysis.matchScore)||0,metadata:{metrics:m,fileName:String(b.fileName||"").slice(0,180)}})}catch{}return NextResponse.json({ok:true,analysis,pro,unlimited:pro})}
